import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { MainMenu } from "@/components/MainMenu";
import { AuthProvider } from "@/components/providers";

import "@/styles/global.scss";

const robotoFont = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Abelohost Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${robotoFont.variable}`}>
      <body>
        <Header />
        <MainMenu />
        <main>
          <AuthProvider>
            {children}
          </AuthProvider>
        </main>
        <Footer />
      </body>
    </html>
  );
}
